export type ServiceCategory =
  | "start"
  | "registered-agent"
  | "federal"
  | "expand"
  | "manage"
  | "close"
  | "renewal"
  | "phone-mail"
  | "business-supplies"
  | "trade-names"
  | "more";

export type Service = {
  id: string;
  name: string;
  description: string;
  price: number;
  category: ServiceCategory;
  categoryLabel: string;
  raincEndpoint: string;
  raincServiceType: string;
  popular?: boolean;
  recurring?: boolean;
  recurringLabel?: string;
};

export const SERVICE_CATEGORIES: { id: ServiceCategory; label: string; description: string }[] = [
  { id: "start", label: "Start Your Business", description: "Form and launch your company" },
  { id: "registered-agent", label: "Registered Agent Services", description: "Maintain your legal compliance" },
  { id: "federal", label: "Federal Filings & Reports", description: "Federal tax IDs and government filings" },
  { id: "expand", label: "Expand Your Business", description: "Register in new states and get certifications" },
  { id: "manage", label: "Manage Your Business", description: "Amendments, certificates, and copies" },
  { id: "renewal", label: "Renewal Services", description: "Keep your business in good standing" },
  { id: "close", label: "Close Your Business", description: "Dissolution and withdrawal filings" },
  { id: "phone-mail", label: "Phone & Mail Services", description: "Virtual office and mail scanning services" },
  { id: "business-supplies", label: "Business Supplies", description: "Corporate books, seals, and certificates" },
  { id: "trade-names", label: "Trade Names (DBA)", description: "Register and publish trade names" },
  { id: "more", label: "More Services", description: "Additional business services" },
];

export const SERVICES: Service[] = [
  {
    id: "business-formation",
    name: "Business Formation Service",
    description: "Fast, easy business formation. Includes a business address, mail scanning, complete legal forms library, and 24/7 expert support. Your information stays private and protected.",
    price: 149,
    category: "start",
    categoryLabel: "Start Your Business",
    raincEndpoint: "/services",
    raincServiceType: "form a company",
    popular: true,
  },
  {
    id: "registered-agent-service",
    name: "Registered Agent Service",
    description: "Professional registered agent service to receive legal documents and government notices on your behalf. Stay compliant and protect your privacy.",
    price: 129,
    category: "registered-agent",
    categoryLabel: "Registered Agent Services",
    raincEndpoint: "/services",
    raincServiceType: "registered agent",
    popular: true,
    recurring: true,
    recurringLabel: "/year",
  },
  {
    id: "change-registered-agent",
    name: "Change Registered Agent Filing",
    description: "File the official state paperwork to change your registered agent to a new provider. Includes state filing fees.",
    price: 75,
    category: "registered-agent",
    categoryLabel: "Registered Agent Services",
    raincEndpoint: "/services",
    raincServiceType: "change registered agent",
  },
  {
    id: "registered-agent-resignation",
    name: "Registered Agent Resignation Filing",
    description: "Officially resign as a registered agent with the state. Required when changing or removing a registered agent.",
    price: 99,
    category: "registered-agent",
    categoryLabel: "Registered Agent Services",
    raincEndpoint: "/services",
    raincServiceType: "registered agent resignation",
  },
  {
    id: "boc3",
    name: "BOC-3 Blanket Agent Service",
    description: "Required for FMCSA authority applicants. Designate process agents in all US states and territories with a single blanket filing.",
    price: 150,
    category: "registered-agent",
    categoryLabel: "Registered Agent Services",
    raincEndpoint: "/services",
    raincServiceType: "boc3",
  },
  {
    id: "dc-agent",
    name: "DC Agent for Service of Process",
    description: "Required for companies doing business in Washington DC. Designate a DC-based agent for service of process.",
    price: 149,
    category: "registered-agent",
    categoryLabel: "Registered Agent Services",
    raincEndpoint: "/services",
    raincServiceType: "dc agent",
  },
  {
    id: "ein",
    name: "EIN – Tax ID Number",
    description: "Obtain your federal Employer Identification Number (EIN) from the IRS. Required to open a business bank account, hire employees, and file taxes.",
    price: 79,
    category: "federal",
    categoryLabel: "Federal Filings & Reports",
    raincEndpoint: "/services",
    raincServiceType: "ein",
    popular: true,
  },
  {
    id: "ein-non-us",
    name: "EIN – Tax ID Number for Non-US Citizens",
    description: "EIN service tailored for non-US citizens and foreign nationals who need a federal Tax ID number for their US business.",
    price: 249,
    category: "federal",
    categoryLabel: "Federal Filings & Reports",
    raincEndpoint: "/services",
    raincServiceType: "ein non-us",
  },
  {
    id: "ein-amendment",
    name: "EIN Amendment: 8822-B",
    description: "Update your EIN registration details with the IRS using Form 8822-B. Required when your business address, entity type, or responsible party changes.",
    price: 99,
    category: "federal",
    categoryLabel: "Federal Filings & Reports",
    raincEndpoint: "/services",
    raincServiceType: "ein amendment",
  },
  {
    id: "s-corp-election",
    name: "S Corporation Election",
    description: "File IRS Form 2553 to elect S-Corporation tax status for your LLC or corporation. Can save thousands in self-employment taxes.",
    price: 199,
    category: "federal",
    categoryLabel: "Federal Filings & Reports",
    raincEndpoint: "/services",
    raincServiceType: "s corp election",
  },
  {
    id: "beneficial-ownership",
    name: "Beneficial Ownership Filing",
    description: "File your company's Beneficial Ownership Information (BOI) report with FinCEN as required under the Corporate Transparency Act.",
    price: 99,
    category: "federal",
    categoryLabel: "Federal Filings & Reports",
    raincEndpoint: "/services",
    raincServiceType: "beneficial ownership",
    popular: true,
  },
  {
    id: "beneficial-ownership-amendment",
    name: "Beneficial Ownership Amendment",
    description: "Update your Beneficial Ownership Information report when ownership or key details change. Required within 30 days of changes.",
    price: 99,
    category: "federal",
    categoryLabel: "Federal Filings & Reports",
    raincEndpoint: "/services",
    raincServiceType: "beneficial ownership amendment",
  },
  {
    id: "foreign-registration",
    name: "Register a Company – Foreign Registration",
    description: "Qualify your existing company to do business in a new state. Required when operating outside your home state of formation.",
    price: 199,
    category: "expand",
    categoryLabel: "Expand Your Business",
    raincEndpoint: "/services",
    raincServiceType: "foreign registration",
  },
  {
    id: "apostille",
    name: "Apostille",
    description: "Authenticate your business documents for international use. Required for companies operating or contracting in foreign countries.",
    price: 599,
    category: "expand",
    categoryLabel: "Expand Your Business",
    raincEndpoint: "/services",
    raincServiceType: "apostille",
  },
  {
    id: "good-standing",
    name: "Certificate of Good Standing",
    description: "Obtain an official state-issued certificate confirming your company is in good standing. Often required by banks, investors, and partners.",
    price: 99,
    category: "manage",
    categoryLabel: "Manage Your Business",
    raincEndpoint: "/services",
    raincServiceType: "certificate of good standing",
    popular: true,
  },
  {
    id: "amendment",
    name: "Amendment",
    description: "File an official amendment to update your company's articles of organization or incorporation. Required when changing your company name, structure, or key details.",
    price: 149,
    category: "manage",
    categoryLabel: "Manage Your Business",
    raincEndpoint: "/services",
    raincServiceType: "amendment",
  },
  {
    id: "certified-copy",
    name: "Certified Copy",
    description: "Obtain a certified copy of your formation documents directly from the state. Required by banks, courts, and government agencies.",
    price: 99,
    category: "manage",
    categoryLabel: "Manage Your Business",
    raincEndpoint: "/services",
    raincServiceType: "certified copy",
  },
  {
    id: "renewal",
    name: "Renewal Filings",
    description: "File your annual or biennial report to keep your company in good standing with the state. Avoid penalties and administrative dissolution.",
    price: 100,
    category: "renewal",
    categoryLabel: "Renewal Services",
    raincEndpoint: "/services",
    raincServiceType: "renewal",
    recurring: true,
    recurringLabel: "/year",
  },
  {
    id: "initial-report",
    name: "Initial Report Filing",
    description: "File the required initial report after company formation in states that require it. Establishes your company's official record with the state.",
    price: 99,
    category: "renewal",
    categoryLabel: "Renewal Services",
    raincEndpoint: "/services",
    raincServiceType: "initial report",
  },
  {
    id: "dissolution",
    name: "Company Dissolution Filing",
    description: "Officially dissolve your company with the state. Properly closing your business protects you from ongoing fees, taxes, and legal liability.",
    price: 149,
    category: "close",
    categoryLabel: "Close Your Business",
    raincEndpoint: "/services",
    raincServiceType: "dissolution",
  },
  {
    id: "withdrawal",
    name: "Business Registration – Withdrawal Filing",
    description: "Withdraw your foreign registration from a state where you no longer do business. Stops ongoing state fees and reporting requirements.",
    price: 149,
    category: "close",
    categoryLabel: "Close Your Business",
    raincEndpoint: "/services",
    raincServiceType: "withdrawal",
  },
  {
    id: "mail-scanning",
    name: "Mail Scanning Service",
    description: "Get your business mail scanned and delivered digitally. Never miss an important document with our secure mail scanning and forwarding service.",
    price: 99,
    category: "phone-mail",
    categoryLabel: "Phone & Mail Services",
    raincEndpoint: "/services",
    raincServiceType: "mail scanning",
    recurring: true,
    recurringLabel: "/year",
  },
  {
    id: "virtual-office-mail-scanning",
    name: "Virtual Office With Mail Scanning",
    description: "A prestigious business address with full mail scanning service. Use our address for your business registration, banking, and correspondence.",
    price: 149,
    category: "phone-mail",
    categoryLabel: "Phone & Mail Services",
    raincEndpoint: "/services",
    raincServiceType: "virtual office",
    popular: true,
    recurring: true,
    recurringLabel: "/year",
  },
  {
    id: "virtual-office-pro",
    name: "Virtual Office Pro",
    description: "Business address with 25 mail scans per year. Ideal for businesses with moderate mail volume that need a professional US address.",
    price: 199,
    category: "phone-mail",
    categoryLabel: "Phone & Mail Services",
    raincEndpoint: "/services",
    raincServiceType: "virtual office pro",
    recurring: true,
    recurringLabel: "/year",
  },
  {
    id: "virtual-office-unlimited",
    name: "Virtual Office Unlimited",
    description: "Business address with unlimited mail scanning. Perfect for high-volume mail users who need maximum flexibility.",
    price: 59,
    category: "phone-mail",
    categoryLabel: "Phone & Mail Services",
    raincEndpoint: "/services",
    raincServiceType: "virtual office unlimited",
    recurring: true,
    recurringLabel: "/month",
  },
  {
    id: "gobook",
    name: "GoBook",
    description: "A professional corporate record book to organize and store your important business documents, minutes, and resolutions.",
    price: 49,
    category: "business-supplies",
    categoryLabel: "Business Supplies",
    raincEndpoint: "/services",
    raincServiceType: "gobook",
  },
  {
    id: "gobook-and-seal",
    name: "GoBook and Seal",
    description: "Corporate record book bundled with a professional embossing seal. Everything you need to maintain your corporate records in style.",
    price: 79,
    category: "business-supplies",
    categoryLabel: "Business Supplies",
    raincEndpoint: "/services",
    raincServiceType: "gobook and seal",
  },
  {
    id: "corporate-seal",
    name: "Corporate Seal",
    description: "A professional embossing seal for your company documents. Required by some states and lenders to authenticate official business documents.",
    price: 39,
    category: "business-supplies",
    categoryLabel: "Business Supplies",
    raincEndpoint: "/services",
    raincServiceType: "corporate seal",
  },
  {
    id: "corporate-book",
    name: "Corporate Book",
    description: "A traditional corporate record binder to keep your formation documents, meeting minutes, and ownership records organized.",
    price: 49,
    category: "business-supplies",
    categoryLabel: "Business Supplies",
    raincEndpoint: "/services",
    raincServiceType: "corporate book",
  },
  {
    id: "corporate-book-and-seal",
    name: "Corporate Book and Seal",
    description: "Complete corporate kit with a record binder and embossing seal. Ideal for corporations maintaining formal records.",
    price: 79,
    category: "business-supplies",
    categoryLabel: "Business Supplies",
    raincEndpoint: "/services",
    raincServiceType: "corporate book and seal",
  },
  {
    id: "certificates-x10",
    name: "Certificates x10",
    description: "A set of 10 professional stock or membership certificates for your company. Used to document ownership interests in your business.",
    price: 29,
    category: "business-supplies",
    categoryLabel: "Business Supplies",
    raincEndpoint: "/services",
    raincServiceType: "certificates",
  },
  {
    id: "corporate-kit",
    name: "Corporate Kit",
    description: "Complete corporate bundle including a record book, embossing seal, and 10 certificates. Everything you need to maintain proper corporate records.",
    price: 99,
    category: "business-supplies",
    categoryLabel: "Business Supplies",
    raincEndpoint: "/services",
    raincServiceType: "corporate kit",
  },
  {
    id: "dba-trade-name-filing",
    name: "DBA Trade Name Filing",
    description: "Register a fictitious business name (DBA) with the state or county. Required to operate under a name different from your legal entity name.",
    price: 149,
    category: "trade-names",
    categoryLabel: "Trade Names (DBA)",
    raincEndpoint: "/services",
    raincServiceType: "dba trade name filing",
  },
  {
    id: "trade-name-publication",
    name: "Trade Name Publication Service",
    description: "Publish your DBA or trade name in an approved local newspaper as required by some states. Fulfills the legal publication requirement.",
    price: 150,
    category: "trade-names",
    categoryLabel: "Trade Names (DBA)",
    raincEndpoint: "/services",
    raincServiceType: "trade name publication",
  },
  {
    id: "dba-complete-package",
    name: "DBA Complete Package",
    description: "All-in-one DBA bundle: state filing plus newspaper publication. Everything required to legally operate under a trade name in states with publication requirements.",
    price: 249,
    category: "trade-names",
    categoryLabel: "Trade Names (DBA)",
    raincEndpoint: "/services",
    raincServiceType: "dba complete package",
  },
  {
    id: "business-reinstatement",
    name: "Business Reinstatement Filing",
    description: "Reinstate a dissolved or revoked business entity back to active status with the state. Includes all required state filings.",
    price: 199,
    category: "more",
    categoryLabel: "More Services",
    raincEndpoint: "/services",
    raincServiceType: "business reinstatement",
  },
  {
    id: "publication-service",
    name: "Publication Service",
    description: "Fulfill mandatory state publication requirements for your LLC or corporation. We handle the newspaper publication process on your behalf.",
    price: 200,
    category: "more",
    categoryLabel: "More Services",
    raincEndpoint: "/services",
    raincServiceType: "publication service",
  },
  {
    id: "domestication-filing",
    name: "Domestication Filing",
    description: "Transfer your business entity from one state to another while maintaining the same legal entity. Ideal for relocating your company.",
    price: 299,
    category: "more",
    categoryLabel: "More Services",
    raincEndpoint: "/services",
    raincServiceType: "domestication filing",
  },
  {
    id: "business-records-copies",
    name: "Business Records Copies",
    description: "Obtain copies of your business formation documents and records directly from the state filing office.",
    price: 99,
    category: "more",
    categoryLabel: "More Services",
    raincEndpoint: "/services",
    raincServiceType: "business records copies",
  },
  {
    id: "amended-annual-report",
    name: "Amended Annual Report",
    description: "File an amendment to a previously submitted annual report to correct or update information on file with the state.",
    price: 100,
    category: "more",
    categoryLabel: "More Services",
    raincEndpoint: "/services",
    raincServiceType: "amended annual report",
  },
];

export function getServicesByCategory(category: ServiceCategory): Service[] {
  return SERVICES.filter((s) => s.category === category);
}
