import type { EventDefinition } from "./types";

export const FINAL_TRIGGER_EVENT_MAP: EventDefinition[] = [
  { name: "account_created", category: "account_auth", description: "New account created." },
  { name: "email_verification_requested", category: "account_auth", description: "Verification email requested." },
  { name: "email_verification_completed", category: "account_auth", description: "Email verification completed." },
  { name: "email_verification_expired", category: "account_auth", description: "Verification expired after 48h." },
  { name: "password_reset_requested", category: "account_auth", description: "Password reset started." },
  { name: "password_reset_completed", category: "account_auth", description: "Password reset done." },
  { name: "new_device_login", category: "account_auth", description: "Login from a new device." },
  { name: "account_deletion_requested", category: "account_auth", description: "Deletion request submitted." },
  { name: "account_deletion_confirmed", category: "account_auth", description: "Deletion completed." },
  { name: "profile_incomplete", category: "onboarding_activation", description: "Profile still incomplete at checkpoint." },
  { name: "profile_completed", category: "onboarding_activation", description: "Profile completed." },
  { name: "onboarding_started", category: "onboarding_activation", description: "Onboarding started." },
  { name: "onboarding_completed", category: "onboarding_activation", description: "Onboarding completed." },
  { name: "free_account_inactive_7d", category: "onboarding_activation", description: "Free account inactive for 7 days." },
  { name: "free_account_inactive_14d", category: "onboarding_activation", description: "Free account inactive for 14 days." },
  { name: "free_account_inactive_30d", category: "onboarding_activation", description: "Free account inactive for 30 days." },
  { name: "consultation_booked", category: "onboarding_activation", description: "Consultation booked." },
  { name: "consultation_missed", category: "onboarding_activation", description: "Consultation missed." },
  { name: "consultation_completed", category: "onboarding_activation", description: "Consultation completed." },
  { name: "checkout_started", category: "checkout_monetization", description: "Checkout started." },
  { name: "checkout_abandoned", category: "checkout_monetization", description: "Checkout abandoned." },
  { name: "plan_purchased", category: "checkout_monetization", description: "Plan purchased." },
  { name: "payment_failed", category: "checkout_monetization", description: "Payment failed." },
  { name: "payment_recovered", category: "checkout_monetization", description: "Payment recovered." },
  { name: "subscription_renewal_upcoming", category: "checkout_monetization", description: "Renewal in 30 days." },
  { name: "subscription_renewed", category: "checkout_monetization", description: "Subscription renewed." },
  { name: "subscription_canceled", category: "checkout_monetization", description: "Subscription canceled." },
  { name: "subscription_reactivated", category: "checkout_monetization", description: "Subscription reactivated." },
  { name: "formation_order_placed", category: "formation_service_delivery", description: "Formation order placed." },
  { name: "documents_requested", category: "formation_service_delivery", description: "Docs requested." },
  { name: "documents_uploaded", category: "formation_service_delivery", description: "Docs uploaded." },
  { name: "documents_missing_48h", category: "formation_service_delivery", description: "Docs missing after 48h." },
  { name: "documents_missing_7d", category: "formation_service_delivery", description: "Docs missing after 7 days." },
  { name: "formation_submitted", category: "formation_service_delivery", description: "Formation submitted to state." },
  { name: "formation_approved", category: "formation_service_delivery", description: "Formation approved." },
  { name: "formation_rejected", category: "formation_service_delivery", description: "Formation rejected." },
  { name: "ein_application_started", category: "formation_service_delivery", description: "EIN application started." },
  { name: "ein_delayed_30d", category: "formation_service_delivery", description: "EIN delayed 30d." },
  { name: "ein_received", category: "formation_service_delivery", description: "EIN received." },
  { name: "boi_filing_required", category: "formation_service_delivery", description: "BOI filing required." },
  { name: "boi_filing_completed", category: "formation_service_delivery", description: "BOI filing completed." },
  { name: "boi_filing_exempt", category: "formation_service_delivery", description: "BOI exempt." },
  { name: "registered_agent_activated", category: "compliance_ongoing", description: "RA activated." },
  { name: "registered_agent_canceled", category: "compliance_ongoing", description: "RA canceled." },
  { name: "annual_report_due_60d", category: "compliance_ongoing", description: "Annual report due in 60 days." },
  { name: "annual_report_due_30d", category: "compliance_ongoing", description: "Annual report due in 30 days." },
  { name: "annual_report_due_14d", category: "compliance_ongoing", description: "Annual report due in 14 days." },
  { name: "annual_report_due_3d", category: "compliance_ongoing", description: "Annual report due in 3 days." },
  { name: "annual_report_filed", category: "compliance_ongoing", description: "Annual report filed." },
  { name: "annual_report_overdue", category: "compliance_ongoing", description: "Annual report overdue." },
  { name: "compliance_issue_detected", category: "compliance_ongoing", description: "Compliance issue detected." },
  { name: "compliance_risk_level_changed", category: "compliance_ongoing", description: "Risk level changed." },
  { name: "banking_readiness_eligible", category: "banking_financial", description: "Banking readiness eligible." },
  { name: "banking_application_started", category: "banking_financial", description: "Banking application started." },
  { name: "banking_approved", category: "banking_financial", description: "Banking approved." },
  { name: "banking_rejected", category: "banking_financial", description: "Banking rejected." },
  { name: "stripe_readiness_eligible", category: "banking_financial", description: "Stripe readiness eligible." },
  { name: "bookkeeping_onboarding_started", category: "bookkeeping_tax", description: "Bookkeeping onboarding started." },
  { name: "bookkeeping_onboarding_incomplete_7d", category: "bookkeeping_tax", description: "Bookkeeping onboarding incomplete 7d." },
  { name: "bookkeeping_active", category: "bookkeeping_tax", description: "Bookkeeping active." },
  { name: "monthly_report_ready", category: "bookkeeping_tax", description: "Monthly report ready." },
  { name: "tax_season_approaching", category: "bookkeeping_tax", description: "Tax season approaching." },
  { name: "tax_filing_required", category: "bookkeeping_tax", description: "Tax filing required." },
  { name: "tax_filing_completed", category: "bookkeeping_tax", description: "Tax filing completed." },
  { name: "support_ticket_opened", category: "support_engagement_edge", description: "Support ticket opened." },
  { name: "support_ticket_resolved", category: "support_engagement_edge", description: "Support ticket resolved." },
  { name: "nps_survey_eligible", category: "support_engagement_edge", description: "NPS survey eligible." },
  { name: "referral_eligible", category: "support_engagement_edge", description: "Referral eligible." },
  { name: "dormancy_30d", category: "support_engagement_edge", description: "Dormant 30 days." },
  { name: "dormancy_60d", category: "support_engagement_edge", description: "Dormant 60 days." },
  { name: "dormancy_90d", category: "support_engagement_edge", description: "Dormant 90 days." },
  { name: "upgrade_eligible", category: "support_engagement_edge", description: "Upgrade eligible." },
  { name: "cross_sell_eligible", category: "support_engagement_edge", description: "Cross-sell eligible." },
];
