export const LIFECYCLE_SEQUENCES = [
  {
    id: "A",
    name: "Free Account Welcome and Activation",
    trigger: "account_created + email_verification_completed + no plan_purchased",
    flow: ["Day 0 ONB-01", "Day 1 ONB-02 if profile incomplete", "Day 3 ONB-03", "Day 7 ONB-04 if no checkout", "Day 14 ACT-04 if still no checkout"],
    exit: ["checkout_started", "plan_purchased", "sequence end day 14"],
  },
  {
    id: "B",
    name: "Abandoned Cart Recovery",
    trigger: "checkout_started + no plan_purchased within 1h",
    flow: ["Hour 1 ACT-01", "Hour 24 ACT-02 if still no purchase"],
    exit: ["plan_purchased", "sequence end after ACT-02"],
  },
  {
    id: "C",
    name: "Formation Status Journey",
    trigger: "plan_purchased (formation)",
    flow: ["Immediate FRM-01", "FRM-02 loop for missing docs", "FRM-03 on formation_submitted", "FRM-04 on formation_approved", "FRM-05 on formation_rejected"],
    exit: ["formation_approved", "formation_rejected handled"],
  },
  {
    id: "D",
    name: "EIN Application and Delay Management",
    trigger: "formation_approved",
    flow: ["Immediate EIN-01", "Day 30 EIN-02 if pending", "EIN-03 on ein_received"],
    exit: ["ein_received"],
  },
  {
    id: "E",
    name: "Compliance Countdown",
    trigger: "annual_report_due_date within 60 days and not filed",
    flow: ["CMP-01 at 60d", "CMP-02 at 30d", "CMP-03 at 14d", "CMP-04 at 3d"],
    exit: ["annual_report_filed", "deadline passed"],
  },
  {
    id: "F",
    name: "Failed Payment and Dunning",
    trigger: "payment_failed",
    flow: ["BIL-02 immediate", "BIL-03 day 3", "BIL-04 day 7", "CHN-03 day 14 if unresolved"],
    exit: ["payment_recovered", "subscription_canceled involuntary"],
  },
  {
    id: "G",
    name: "BOI Filing",
    trigger: "formation_approved",
    flow: ["BOI-01 after formation", "Reminder if not completed", "BOI-02 on completion"],
    exit: ["boi_filing_completed", "boi_filing_exempt"],
  },
  {
    id: "H",
    name: "Banking Readiness",
    trigger: "ein_received",
    flow: ["BKG-01 day 1", "Reminder at day 14 if no action", "BKG-02 on rejection"],
    exit: ["banking_approved", "banking_application_started", "manual dismiss"],
  },
  {
    id: "I",
    name: "Re-engagement",
    trigger: "dormancy_60d",
    flow: ["Re-engagement email day 0", "Final nudge day 14", "Sunset policy at day 30 if no activity"],
    exit: ["login", "click", "purchase"],
  },
] as const;
